// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  input: dynamic(() => import("./Input")),
  rich_text: dynamic(() => import("./RichText")),
  showcase: dynamic(() => import("./Showcase")),
};
